networks:
  app.net:
    driver: bridge

services:
  php:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "41257:80"
    volumes:
      - ./core/public:/var/www/html
      - ./core/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - app.net
    depends_on:
      - mysql

  adminer:
    image: adminer:5.2.1
    ports:
      - "13780:8080"
    networks:
      - app.net

  mysql:
    image: mysql:8.0
    env_file:
      - core/.env
    networks:
      - app.net
    volumes:
      - ./core/sql/schemas.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./core/sql/data.sql:/docker-entrypoint-initdb.d/02_data.sql

  client:
    image : nginx:alpine
    ports:
      - "58962:80"
    volumes:
      - ./web/:/usr/share/nginx/html
      - ./web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app.net
    depends_on:
      - php
