networks:
  app.net:
    driver: bridge

services:
  php:
    image: operrin/php:8.4.6
    ports:
      - "88:80"
    volumes :
      - ./public:/var/www/html
      - ./src:/var/www/src
    working_dir: /var/www/src
    networks:
      - app.net
    depends_on:
      - mysql
    command: sh -c  "composer install&&php -S 0.0.0.0:80 -t /var/www/html"

  adminer:
    image: adminer:5.2.1
    ports:
      - "8888:8080"
    networks:
      - app.net

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3333:3306"
    networks:
      - app.net
    volumes:
      - ./sql/gift.schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/gift.data.sql:/docker-entrypoint-initdb.d/02_data.sql
