networks:
  app.net:
    driver: bridge

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "89:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    working_dir: /var/www/src
    networks:
      - app.net
    depends_on:
      - mysql
    restart: always

  adminer:
    image: adminer:5.2.1
    ports:
      - "8889:8080"
    networks:
      - app.net
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    env_file:
      - .env
    ports:
      - "3334:3306"
    networks:
      - app.net
    volumes:
      - ./sql/schemas.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/02_data.sql
    restart: always
